In [131]:
%matplotlib inline
import numpy as np
import pandas as pd
np.random.seed(3)

In [132]:
# question 1
rolls = np.random.choice([1, 2, 3, 4, 5, 6], size=(10_000, 2))
(rolls[:,0] == rolls[:,1]).mean()

0.1711

In [133]:
# question 2
# 1. represent our data -- 0 is tails, 1 is heads
# 2. create a matrix (nrows, ncols)
flips = np.random.choice([0, 1], size=(10_000, 8))
flips

array([[0, 1, 1, ..., 1, 0, 1],
       [0, 1, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0]])

In [134]:

simulation_results = flips.sum(axis=1)
(simulation_results == 3).mean()

0.2242

In [135]:
(simulation_results > 3).mean()

0.6381

In [165]:
# question 3
np.random.seed(3)
# 1. Represent our data 0 - Web Development, 1- Data Science,
# 2. Generate the matrix
billboards = np.random.choice([0, 1], p=[.75, .25], size=(10_000, 2))
billboards

array([[0, 0],
       [0, 0],
       [1, 1],
       ...,
       [0, 0],
       [1, 0],
       [1, 1]])

In [166]:
billboards = billboards.sum(axis=1)
billboards
(billboards == 2).mean()

0.061

In [212]:
# question 4
np.random.seed(3)
pt_consumption = np.round(np.random.normal(3, 1.5, (10000, 5)))
pt_consumption

array([[6., 4., 3., 0., 3.],
       [2., 3., 2., 3., 2.],
       [1., 4., 4., 6., 3.],
       ...,
       [4., 1., 4., 2., 4.],
       [4., 2., 2., 1., 4.],
       [5., 1., 0., 2., 1.]])

In [213]:
(pt_consumption.sum(axis=1) < 17).mean()

0.6757

In [220]:
# question 5
np.random.seed(3)
men_heights = np.random.normal(178, 8, 10000)
women_heights = np.random.normal(170, 6, 10000)
men_heights
women_heights

array([169.75074935, 159.04086632, 164.93118902, ..., 167.71134257,
       173.3153846 , 173.35826653])

In [222]:
(women_heights > men_heights).mean()

0.219

In [234]:
#question 6
(249/250)**50

0.8184024506760997

In [235]:
(249/250)**100

0.6697825712726458

In [243]:
1 - (249/250)**150

0.4518483022503271

In [245]:
(249/250)**450 

0.1647032961586129

In [289]:
np.random.seed(3)
s = np.random.choice([0,1],p = [1/250, 249/250], size = (10000, 50))
s

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [290]:
(s.sum(axis=1) == 50).mean()

0.8203

In [291]:
s = np.random.choice([0,1],p = [1/250, 249/250], size = (10000, 100))

In [292]:
(s.sum(axis=1) == 100).mean()

0.6677

In [295]:
s = np.random.choice([0,1],p = [1/250, 249/250], size = (10000, 150))

In [296]:
1 - (s.sum(axis=1) == 150).mean()

0.4547

In [313]:
s = np.random.choice([0,1],p = [1/250, 249/250], size = (10000, 450))
s

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [314]:
(s.sum(axis=1) == 450).mean()

0.1659

In [318]:
# question 7
food_truck = np.random.choice([0,1],p = [0.3, 0.7], size = (10000, 3))
(food_truck.sum(axis=1) == 0).mean()

0.027

In [322]:
food_truck = np.random.choice([0,1],p = [0.3, 0.7], size = (10000, 7))
1 - (food_truck.sum(axis=1) == 0).mean()

0.9999

In [388]:
rows = np.random.choice(range(1,366), size = (10000,23))
rows

array([[175, 227,  23, ..., 147, 165, 110],
       [274, 159, 230, ...,   3,  40, 180],
       [357, 284, 303, ..., 239,   7,  58],
       ...,
       [152, 265, 354, ..., 127, 294,  83],
       [ 15, 234, 207, ...,  84, 248, 147],
       [ 23,  24,  94, ..., 244,  99,  87]])

In [412]:
df = pd.DataFrame(rows)
s = df.iloc[0, :]
s.nunique() == 23

False