In [444]:
%matplotlib inline
import numpy as np
import pandas as pd
np.random.seed(3)

In [445]:
# question 1
rolls = np.random.choice([1, 2, 3, 4, 5, 6], size=(10_000, 2))
(rolls[:,0] == rolls[:,1]).mean()

0.1711

In [133]:
# question 2
# 1. represent our data -- 0 is tails, 1 is heads
# 2. create a matrix (nrows, ncols)
flips = np.random.choice([0, 1], size=(10_000, 8))
flips

array([[0, 1, 1, ..., 1, 0, 1],
       [0, 1, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0]])

In [134]:

simulation_results = flips.sum(axis=1)
(simulation_results == 3).mean()

0.2242

In [135]:
(simulation_results > 3).mean()

0.6381

In [447]:
# question 3
np.random.seed(3)
# 1. Represent our data 0 - Web Development, 1- Data Science,
# 2. Generate the matrix
billboards = np.random.choice([0, 1], p=[.75, .25], size=(10_000, 2))
billboards

array([[0, 0],
       [0, 0],
       [1, 1],
       ...,
       [0, 0],
       [1, 0],
       [1, 1]])

In [448]:
billboards = billboards.sum(axis=1)
(billboards == 2).mean()

0.061

In [449]:
# question 4
np.random.seed(3)
poptarts = np.round(np.random.normal(3, 1.5, (10000, 5)))
poptarts

array([[6., 4., 3., 0., 3.],
       [2., 3., 2., 3., 2.],
       [1., 4., 4., 6., 3.],
       ...,
       [4., 1., 4., 2., 4.],
       [4., 2., 2., 1., 4.],
       [5., 1., 0., 2., 1.]])

In [450]:
(poptarts.sum(axis=1) < 17).mean()

0.6757

In [455]:
# question 5
np.random.seed(3)
men_heights = np.random.normal(178, 8, 10000)
women_heights = np.random.normal(170, 6, 10000)
men_heights
women_heights

array([169.75074935, 159.04086632, 164.93118902, ..., 167.71134257,
       173.3153846 , 173.35826653])

In [456]:
(women_heights > men_heights).mean()

0.219

In [234]:
#question 6
(249/250)**50

0.8184024506760997

In [235]:
(249/250)**100

0.6697825712726458

In [243]:
1 - (249/250)**150

0.4518483022503271

In [245]:
(249/250)**450 

0.1647032961586129

In [459]:
np.random.seed(3)
s = np.random.choice([0,1],p = [1/250, 249/250], size = (10000, 50))
s

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [460]:
(s.sum(axis=1) == 50).mean()

0.8203

In [291]:
s = np.random.choice([0,1],p = [1/250, 249/250], size = (10000, 100))

In [292]:
(s.sum(axis=1) == 100).mean()

0.6677

In [295]:
s = np.random.choice([0,1],p = [1/250, 249/250], size = (10000, 150))

In [296]:
1 - (s.sum(axis=1) == 150).mean()

0.4547

In [461]:
s = np.random.choice([0,1],p = [1/250, 249/250], size = (10000, 450))

In [462]:
(s.sum(axis=1) == 450).mean()

0.1662

In [318]:
# question 7
food_truck = np.random.choice([0,1],p = [0.3, 0.7], size = (10000, 3))
(food_truck.sum(axis=1) == 0).mean()

0.027

In [322]:
food_truck = np.random.choice([0,1],p = [0.3, 0.7], size = (10000, 7))
1 - (food_truck.sum(axis=1) == 0).mean()

0.9999

In [494]:
# question 8
rows = np.random.choice(range(1,366), size = (10000,23))
rows

array([[276, 341, 113, ..., 267, 321, 306],
       [316, 347,  71, ..., 216, 238, 190],
       [118, 242,  16, ..., 317, 181, 365],
       ...,
       [363, 361, 171, ...,   9,  86, 334],
       [165, 317, 233, ...,  10, 137, 309],
       [321, 168, 199, ..., 365, 160,  91]])

In [495]:
df = pd.DataFrame(rows)
df["n_unique"] = df.nunique(axis=1)
df.head(3)

0    1    2    3    4    5    6    7    8    9  ...   14   15   16   17  \
0  276  341  113  324   10  178  150  250  346  324  ...  243  300  336  251   
1  316  347   71   13  212  102  183  174  346   18  ...  153  222  268  293   
2  118  242   16  288  128   47   85  138   79  261  ...   64  175   44  354   

    18   19   20   21   22  n_unique  
0  207  320  267  321  306        22  
1  359  309  216  238  190        23  
2   40  316  317  181  365        23  

[3 rows x 24 columns]

In [496]:
(df.n_unique == 22).mean()

0.3664

In [499]:
rows = np.random.choice(range(1,366), size = (10000,20))
rows

array([[116, 275, 190, ...,  45,  87, 247],
       [276,  80, 268, ...,  31, 343, 323],
       [254, 263,  16, ...,  31, 161,  81],
       ...,
       [ 73, 296, 129, ...,  56,   1, 325],
       [353, 139,  94, ..., 335,  97, 165],
       [141,  83, 197, ..., 258, 182, 343]])

In [500]:
df = pd.DataFrame(rows)
df["n_unique"] = df.nunique(axis=1)
df.head(3)

0    1    2    3    4    5    6    7    8   9  ...   11   12   13   14  \
0  116  275  190  317   54   66  292  141  115  66  ...  129    9  301   97   
1  276   80  268  339  267  332  116  276  210  68  ...  230  277   89   85   
2  254  263   16  285   74  188   63  154  331  39  ...   16  234  193  274   

    15   16  17   18   19  n_unique  
0  336   33  45   87  247        19  
1    6  191  31  343  323        19  
2  243  143  31  161   81        19  

[3 rows x 21 columns]

In [501]:
(df.n_unique == 19).mean()

0.3201

In [504]:
rows = np.random.choice(range(1,366), size = (10000,40))
rows

array([[ 41, 129,  79, ..., 108, 253, 253],
       [309,  83, 155, ...,  88, 219,   5],
       [ 15, 144, 162, ..., 244,  77,  99],
       ...,
       [103,  31, 265, ..., 157, 299,  22],
       [253, 230, 299, ..., 365, 217,  58],
       [365, 163, 331, ..., 170, 122, 234]])

In [505]:
df = pd.DataFrame(rows)
df["n_unique"] = df.nunique(axis=1)
df.head(3)

0    1    2    3    4    5    6    7    8    9  ...   31   32   33   34  \
0   41  129   79  274  184   44   99  257  255  244  ...  300  262  179  123   
1  309   83  155   57  205  311  271  162  345  314  ...  178  122  359   35   
2   15  144  162  165  236   67  359  280   92  157  ...  125   23  211  107   

    35   36   37   38   39  n_unique  
0  181  199  108  253  253        39  
1  182  134   88  219    5        37  
2    5   76  244   77   99        38  

[3 rows x 41 columns]

In [506]:
(df.n_unique == 39).mean()

0.2653