In [131]:
%matplotlib inline
import numpy as np
import pandas as pd
np.random.seed(3)

In [132]:
# question 1
rolls = np.random.choice([1, 2, 3, 4, 5, 6], size=(10_000, 2))
(rolls[:,0] == rolls[:,1]).mean()

0.1711

In [133]:
# question 2
# 1. represent our data -- 0 is tails, 1 is heads
# 2. create a matrix (nrows, ncols)
flips = np.random.choice([0, 1], size=(10_000, 8))
flips

array([[0, 1, 1, ..., 1, 0, 1],
       [0, 1, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0]])

In [134]:

simulation_results = flips.sum(axis=1)
(simulation_results == 3).mean()

0.2242

In [135]:
(simulation_results > 3).mean()

0.6381

In [165]:
# question 3
np.random.seed(3)
# 1. Represent our data 0 - Web Development, 1- Data Science,
# 2. Generate the matrix
billboards = np.random.choice([0, 1], p=[.75, .25], size=(10_000, 2))
billboards

array([[0, 0],
       [0, 0],
       [1, 1],
       ...,
       [0, 0],
       [1, 0],
       [1, 1]])

In [166]:
billboards = billboards.sum(axis=1)
billboards
(billboards == 2).mean()

0.061

In [212]:
# question 4
np.random.seed(3)
pt_consumption = np.round(np.random.normal(3, 1.5, (10000, 5)))
pt_consumption

array([[6., 4., 3., 0., 3.],
       [2., 3., 2., 3., 2.],
       [1., 4., 4., 6., 3.],
       ...,
       [4., 1., 4., 2., 4.],
       [4., 2., 2., 1., 4.],
       [5., 1., 0., 2., 1.]])

In [213]:
(pt_consumption.sum(axis=1) < 17).mean()

0.6757

In [220]:
# question 5
np.random.seed(3)
men_heights = np.random.normal(178, 8, 10000)
women_heights = np.random.normal(170, 6, 10000)
men_heights
women_heights

array([169.75074935, 159.04086632, 164.93118902, ..., 167.71134257,
       173.3153846 , 173.35826653])

In [222]:
(women_heights > men_heights).mean()

0.219

In [227]:
p_corruption = 1/250
((np.random.random((10000, 50)) < p_corruption).sum(axis=1) == 0).mean()

0.8186